const loveMessages = [
    "You light up my world like nobody else.",
    "Falling in love with you was the easiest thing I've ever done.",
    "I love you more than coffee, but please don't make me prove it.",
    "Your smile is the reason my heart beats.",
    "Being with you makes every day feel like it's Valentine's Day.",
    "I found my home and paradise with you.",
    "Loving you is like breathing; how can I stop?",
    "You are my today and all of my tomorrows.",
    "Life with you is a dream come true.",
    "You have bewitched me, body and soul.",
    "I am who I am because of you.",
    "Every love story is beautiful, but ours is my favorite.",
    "I love you to the moon and back.",
    "You are the last thought in my mind before I drift off to sleep.",
    "With you, I am the best version of myself.",
    "You stole my heart, but I'll let you keep it.",
    "Being with you is the easiest choice I've ever made.",
    "I could start fires with what I feel for you.",
    "You are my favorite notification.",
    "I love you more than pizza, and that's saying a lot.",
    "Every time I see you, I fall in love all over again.",
    "You are my happy place.",
    "Together with you is my favorite place to be.",
    "I still fall for you every day.",
    "You are the reason I wake up with a smile.",
    "Your love is all I need to feel complete.",
    "I will love you until the stars go out.",
    "You make my heart skip a beat.",
    "Your love shines in my heart like the sun shines upon the earth.",
    "Meeting you was like listening to a song for the first time and knowing it would be my favorite.",
    "I am madly in love with you.",
    "You are my dream come true.",
    "Every moment with you is a treasure.",
    "I cherish you more than you can imagine.",
    "I adore you more than any words can express.",
    "With you, every day is a fairytale.",
    "Your love is the most precious gift in my life.",
    "I am yours, and you are mine, forever and always.",
    "You are the reason behind my smile.",
    "I love you for all that you are, all that you have been, and all you're yet to be.",
    "You complete me in a way no one else ever could.",
    "I fall in love with you every time I look into your beautiful eyes.",
    "You are my soulmate, my everything.",
    "Your love makes me stronger and happier.",
    "You are the sunshine in my day and the moonlight in my night.",
    "Every day with you is a wonderful addition to my life's journey.",
    "You're not just my love, you're my heart.",
    "You make me laugh even when I don't want to smile.",
    "My love for you keeps increasing every second.",
    "Your love is like the lamp in the window that guides me home through the darkest night.",
    "I never believed in soulmates until I found you.",
    "You are the best thing that's ever been mine.",
    "I love you more today than yesterday, but not as much as tomorrow.",
    "Let's be weird and wonderful together.",
    "In you, I've found the love of my life and my closest, truest friend.",
    "I choose you. And I'll choose you over and over and over.",
    "Nothing in this world could ever be as wonderful as the love you've given me.",
    "Your love is all I need to feel complete.",
    "I love you not only for what you are, but for what I am when I am with you.",
    "I could hold you forever.",
    "You are my forever confidant. My love for you will end never.",
    "Just seeing your face brightens even the darkest of my days.",
    "Your voice is my favorite sound.",
    "So far, every moment we've spent together has been awesome. But I promise you, the best is yet to come.",
    "If I know what love is, it is because of you.",
    "You do a million little things that bring to joy to my life.",
    "I love you more than I have ever found a way to say to you.",
    "I promise to plant kisses like seeds on your body, so in time you can grow to love yourself as I love you.",
    "With every beat of my heart, I love you more and more.",
    "You're not my number one, you're my only one.",
    "My love for you is a journey; starting at forever, and ending at never.",
    "I never knew what love was until I met you.",
    "Love is not about how many days, months, or years we have been together. Love is about how much we love each other every single day.",
    "You are the reason I believe in love.",
    "Holding your hand makes me the luckiest person in the world because I know I've got the best partner I could ever find.",
    "Every love story is special, unique, and beautiful—but ours is my favorite.",
    "When I look into your eyes, I see a gateway to a world I want to exist in.",
    "I am permanently in love with you, always and forever.",
    "You are my blue crayon, the one I never have enough of, the one I use to color my sky.",
    "Your love is the best part of my day.",
    "Thank you for being my rainbow after the storm.",
    "With you, every moment is sweet and memorable.",
    "I love you more with each passing day.",
    "Your love warms my heart like the sunshine.",
    "Together is my favorite place to be.",
    "You are the reason I believe in love.",
    "Holding your hand is how I want to spend my whole life.",
    "You are my forever and always.",
    "The thought of you brings the biggest smile to my face.",
    "Sending you a little box full of love.",
    "My love for you is a journey, starting at forever and ending at never.",
    "You are the peanut butter to my jelly.",
    "Life with you is a dream I never want to wake up from.",
    "Loving you is as natural as breathing."
  ];
  

const generateButton = document.getElementById('generateButton');
const loveMessage = document.getElementById('loveMessage');

generateButton.addEventListener('click', () => {
    const randomIndex = Math.floor(Math.random() * loveMessages.length);
    loveMessage.textContent = loveMessages[randomIndex];
});
